# This Source Code Form is subject to the terms of the Mozilla Public ---------------------
# License, v. 2.0. If a copy of the MPL was not distributed with this ---------------------
# file, You can obtain one at http://mozilla.org/MPL/2.0/. */ -----------------------------
# ---------------- Copyright (C) 2020 University of Strathclyde and Author ----------------
# -------------------------------- Author: Audrey Berquand --------------------------------
# ------------------------- e-mail: audrey.berquand@strath.ac.uk --------------------------

# --------------------------------------------------------------------------------------------------------------------
# This script allows to define/generate the Knowlegde Graph (KG) structure for an Engineering Model
# based on ECSS_E_TM_10_25_A.
# In KG terms, this script defines the Grakn Schema Layer.
# Based on an export from the UML model of the ECSS_E_TM_10_25_A
# Grakn version: adapted for Grakn 1.8.0
# --------------------------------------------------------------------------------------------------------------------

define

# Attributes Definition

 isArrayBoolean sub attribute, value boolean ;

 isArrayLong sub attribute, value long ;

 isArrayDouble sub attribute, value double ;

  isArrayString  sub attribute, value string ;

  isArrayDate  sub attribute, value string ;

  kind  sub attribute, value string ;

  name  sub attribute, value string ;

  shortName  sub attribute, value string ;

  isSynonym  sub attribute, value boolean ;

  languageCode  sub attribute, value string ;

  content  sub attribute, value string ;

  isTensor  sub attribute, value boolean ;

  hasSingleComponentType  sub attribute, value boolean ;

  rank  sub attribute, value double ;

  dimension  sub isArrayDouble, value string ;

  forwardrelationName  sub attribute, value string ;

  inverserelationName  sub attribute, value string ;

  isAbstract  sub attribute, value boolean ;

  isDeprecated  sub attribute, value boolean ;

  permissibleClass  sub isArrayString, value string ;

  location  sub attribute, value string ;

  isAdaptation  sub attribute, value boolean ;

  remark  sub attribute, value string ;

  isFinalized  sub attribute, value boolean ;

  value  sub isArrayString, value string ;

  conversionFactor  sub attribute, value string ;

  modulus  sub attribute, value string ;

  minContained  sub attribute, value double ;

  maxContained  sub attribute, value double ;

  note  sub isArrayString, value string ;

  example  sub isArrayString, value string ;

  isHidden  sub attribute, value boolean ;

  interfaceEnd  sub attribute, value string ;

  vcardType  sub attribute, value string ;

  studyPhase  sub attribute, value string ;

  engineeringModelIid  sub attribute, value string ;

  sourceEngineeringModelSetupIid  sub attribute, value string ;

  allowMultiSelect  sub attribute, value boolean ;

  externalModelName  sub attribute, value string ;

  externalToolName  sub attribute, value string ;

  externalToolVersion  sub attribute, value string ;

  contentHash  sub attribute, value string ;

  path  sub attribute, value string ;

  createdOn  sub attribute, value string;

  extension  sub attribute, value string ;

  uri  sub attribute, value string ;

  internalThing  sub attribute, value string ;

  externalId  sub attribute, value string ;

  sourceIterationIid  sub attribute, value string ;

  iterationIid  sub attribute, value string ;

  iterationNumber  sub attribute, value double ;

  description  sub attribute, value string ;

  frozenOn  sub attribute, value string ;

  isDeleted  sub attribute, value boolean ;

  logarithmBase  sub attribute, value string ;

  factor  sub attribute, value string ;

  exponent  sub attribute, value string ;

  numberSet  sub attribute, value string ;

  minimumPermissibleValue  sub attribute, value string ;

  isMinimumInclusive  sub attribute, value boolean ;

  maximumPermissibleValue  sub attribute, value string ;

  isMaximumInclusive  sub attribute, value boolean ;

  positiveValueConnotation  sub attribute, value string ;

  negativeValueConnotation  sub attribute, value string ;

  level  sub attribute, value string ;

  affectedItemIid  sub isArrayString, value string ;

  minRelated  sub attribute, value double ;

  maxRelated  sub attribute, value double ;

  nativeName  sub attribute, value string ;

  isVolatile  sub attribute, value boolean ;

  formula  sub attribute, value string ;

  actualValue  sub attribute, value string ;

  useShortNameValues  sub attribute, value boolean ;

  allowDifferentOwnerOfOverride  sub attribute, value boolean ;

  expectsOverride  sub attribute, value boolean ;

  isOptionDependent  sub attribute, value boolean ;

  valueSwitch  sub attribute, value string ;

  computed  sub isArrayString, value string ;

  manual  sub isArrayString, value string ;

  reference  sub isArrayString, value string ;

  numberOfValues  sub attribute, value double ;

  symbol  sub attribute, value string ;

  published  sub isArrayString, value string ;

  isActive  sub attribute, value boolean ;

  accessRight  sub attribute, value string ;

  objectClass  sub attribute, value string ;

  givenName  sub attribute, value string ;

  surname  sub attribute, value string ;

  organizationalUnit  sub attribute, value string ;

  password  sub attribute, value string ;

  quantityDimensionSymbol  sub attribute, value string ;

  quantityDimensionExpression  sub attribute, value string ;

  quantityDimensionExponent  sub isArrayString, value string ;

  versionIdentifier  sub attribute, value string ;

  versionDate  sub attribute, value string ;

  author  sub attribute, value string ;

  publicationYear  sub attribute, value double ;

  language  sub attribute, value string ;

  minReferenced  sub attribute, value double ;

  maxReferenced  sub attribute, value double ;

  relationalOperator  sub attribute, value string ;

  executedOn  sub attribute, value string ;

  status  sub attribute, value string ;

  violatingThing  sub isArrayString, value string ;

  iid  sub attribute, value string ;

  revisionNumber  sub attribute, value double ;

  classKind  sub attribute, value string ;

  lastModifiedOn  sub attribute, value string ;

 # Classes Entities Definition

 ActualFiniteState sub Thing,
    has kind,
    has name,
    has shortName,
    plays iscontained_actualState,
    plays refers_possibleState,
    plays refers_owner,
    plays isrefered_actualState  ; 

 ActualFiniteStateList  sub Thing, 
    has name,
    has shortName,
    plays contains_actualState,
    plays iscontained_actualFiniteStateList,
    plays refers_possibleFiniteStateList,
    plays refers_excludeOption,
    plays refers_owner,
    plays isrefered_stateDependence  ; 

 Alias  sub Thing, 
    has isSynonym,
    has languageCode,
    has content,
    plays iscontained_alias  ; 

 AndExpression  sub BooleanExpression,
    plays refers_term  ; 

 ArrayParameterType  sub CompoundParameterType,
    has isTensor,
    has hasSingleComponentType,
    has rank,
    has dimension  ; 

 BinaryRelationship  sub Relationship,
    plays refers_source,
    plays refers_target;

 BinaryRelationshipRule sub Rule,
    has forwardrelationName,
    has inverserelationName,
    plays refers_relationCategory,
    plays refers_sourceCategory,
    plays refers_targetCategory;

 BooleanExpression sub Thing, abstract,
    plays iscontained_expression,
    plays isrefered_term,
    plays isrefered_topExpression;

 BooleanParameterType  sub ScalarParameterType  ; 

 BuiltInRuleVerification  sub RuleVerification  ; 

 Category  sub DefinedThing,
    has isAbstract,
    has isDeprecated,
    has permissibleClass,
    plays iscontained_definedCategory,
    plays refers_superCategory,
    plays isrefered_relationCategory,
    plays isrefered_sourceCategory,
    plays isrefered_targetCategory,
    plays isrefered_superCategory,
    plays isrefered_category,
    plays isrefered_containingCategory,
    plays isrefered_containedCategory,
    plays isrefered_relatedCategory,
    plays isrefered_referencingCategory,
    plays isrefered_referencedCategory  ; 

 Citation  sub Thing, 
    has location,
    has isAdaptation,
    has remark,
    has shortName,
    plays iscontained_citation,
    plays refers_source;

 CommonFileStore  sub FileStore,
    plays iscontained_commonFileStore  ; 

 CompoundParameterType  sub ParameterType,
    has isFinalized,
    plays contains_component  ; 

 Constant  sub DefinedThing,
    has isDeprecated,
    has value,
    plays iscontained_constant,
    plays refers_parameterType,
    plays refers_scale,
    plays refers_category  ; 

 ConversionBasedUnit  sub MeasurementUnit, abstract,
    has conversionFactor,
    plays refers_referenceUnit  ; 

 CyclicRatioScale  sub RatioScale,
    has modulus  ; 

 DateParameterType  sub ScalarParameterType  ; 

 DateTimeParameterType  sub ScalarParameterType  ; 

 DecompositionRule  sub Rule,
    has minContained,
    has maxContained,
    plays refers_containingCategory,
    plays refers_containedCategory  ; 

 DefinedThing  sub Thing, abstract,
    has name,
    has shortName,
    plays contains_alias,
    plays contains_definition,
    plays contains_hyperLink  ; 

 Definition  sub Thing, 
    has languageCode,
    has content,
    has note,
    has example,
    plays contains_citation,
    plays iscontained_definition  ; 

 DerivedQuantityKind  sub QuantityKind,
    plays contains_quantityKindFactor  ; 

 DerivedUnit  sub MeasurementUnit,
    plays contains_unitFactor  ; 

 DomainFileStore  sub FileStore,
    has isHidden,
    plays iscontained_domainFileStore  ; 

 DomainOfExpertise  sub DefinedThing,
    has isDeprecated,
    plays iscontained_domain,
    plays refers_category,
    plays isrefered_owner,
    plays isrefered_domain,
    plays isrefered_activeDomain,
    plays isrefered_requestedBy,
    plays isrefered_selectedDomain,
    plays isrefered_defaultDomain  ; 

 DomainOfExpertiseGroup  sub DefinedThing,  
    has isDeprecated,
    plays iscontained_domainGroup,
    plays refers_domain;

 ElementBase  sub DefinedThing, abstract,
    plays refers_category,   
    plays refers_owner  ; 

 ElementDefinition  sub ElementBase,   
    plays contains_containedElement,   
    plays contains_parameter,   
    plays contains_parameterGroup,   
    plays iscontained_element,   
    plays refers_referencedElement,   
    plays isrefered_elementDefinition,   
    plays isrefered_topElement,   
    plays isrefered_rootElement; 

 ElementUsage  sub ElementBase,  
    has interfaceEnd,
    plays contains_parameterOverride,   
    plays iscontained_containedElement,   
    plays refers_elementDefinition,   
    plays refers_excludeOption,   
    plays isrefered_elementUsage; 

 EmailAddress  sub Thing, 
    has vcardType,  
    has value,   
    plays iscontained_emailAddress,   
    plays isrefered_defaultEmailAddress  ; 

 EngineeringModel  sub TopContainer,   
    plays contains_commonFileStore,   
    plays contains_logEntry,   
    plays contains_iteration,   
    plays refers_engineeringModelSetup  ; 

 EngineeringModelSetup  sub DefinedThing,  
    has kind,  
    has studyPhase,  
    has engineeringModelIid,  
    has sourceEngineeringModelSetupIid,   
    plays contains_participant,   
    plays contains_requiredRdl,   
    plays contains_iterationSetup,   
    plays iscontained_model,   
    plays refers_activeDomain,   
    plays isrefered_engineeringModelSetup  ; 

 EnumerationParameterType  sub ScalarParameterType,  
    has allowMultiSelect,   
    plays contains_valueDefinition  ; 

 EnumerationValueDefinition  sub DefinedThing,   
    plays iscontained_valueDefinition  ; 

 ExclusiveOrExpression  sub BooleanExpression,   
    plays refers_term  ; 

 ExternalIdentifierMap  sub Thing, 
    has externalModelName,  
    has externalToolName,  
    has externalToolVersion,  
    has name,   
    plays contains_correspondence,   
    plays iscontained_externalIdentifierMap,   
    plays refers_externalFormat,   
    plays refers_owner  ; 

 File  sub Thing,  
    plays contains_fileRevision,   
    plays iscontained_file,   
    plays refers_lockedBy,   
    plays refers_owner,   
    plays refers_category  ; 

 FileRevision  sub Thing, 
    has contentHash,  
    has path,  
    has createdOn,  
    has name,   
    plays iscontained_fileRevision,   
    plays refers_creator,   
    plays refers_containingFolder,   
    plays refers_fileType  ; 

 FileStore  sub Thing, abstract,
    has name,  
    has createdOn,   
    plays contains_folder,   
    plays contains_file,   
    plays refers_owner  ; 

 FileType  sub DefinedThing,  
    has extension,  
    has isDeprecated,   
    plays iscontained_fileType,   
    plays refers_category,   
    plays isrefered_fileType  ; 

 Folder  sub Thing, 
    has path,  
    has name,  
    has createdOn,   
    plays iscontained_folder,   
    plays refers_creator,   
    plays refers_containingFolder,   
    plays refers_owner,   
    plays isrefered_containingFolder  ; 

 Glossary  sub DefinedThing,  
    has isDeprecated,   
    plays contains_term,   
    plays iscontained_glossary,   
    plays refers_category  ; 

 HyperLink  sub Thing, 
    has uri,  
    has languageCode,  
    has content,   
    plays iscontained_hyperLink  ; 

 IdCorrespondence  sub Thing, 
    has internalThing,  
    has externalId,   
    plays iscontained_correspondence,   
    plays refers_owner  ; 

 IntervalScale  sub MeasurementScale  ; 

 Iteration  sub Thing, 
    has sourceIterationIid,   
    plays contains_option,   
    plays contains_publication,   
    plays contains_possibleFiniteStateList,   
    plays contains_element,   
    plays contains_relation,   
    plays contains_externalIdentifierMap,   
    plays contains_requirementsSpecification,   
    plays contains_domainFileStore,   
    plays contains_actualFiniteStateList,   
    plays contains_ruleVerificationList,   
    plays iscontained_iteration,   
    plays refers_iterationSetup,   
    plays refers_topElement,   
    plays refers_defaultOption  ; 

 IterationSetup  sub Thing, 
    has iterationIid,  
    has iterationNumber,  
    has description,  
    has frozenOn,  
    has isDeleted,  
    has createdOn,  
    plays iscontained_iterationSetup,   
    plays refers_sourceIterationSetup,   
    plays isrefered_iterationSetup,   
    plays isrefered_sourceIterationSetup  ; 

 LinearConversionUnit  sub ConversionBasedUnit  ; 

 LogarithmicScale  sub MeasurementScale,  
    has logarithmBase,  
    has factor,  
    has exponent,   
    plays contains_referenceQuantityValue,   
    plays refers_referenceQuantityKind  ; 

 MappingToReferenceScale  sub Thing,  
    plays iscontained_mappingToReferenceScale,   
    plays refers_referenceScaleValue,   
    plays refers_dependentScaleValue  ; 

 MeasurementScale  sub DefinedThing, abstract,
    has numberSet,  
    has minimumPermissibleValue,  
    has isMinimumInclusive,  
    has maximumPermissibleValue,  
    has isMaximumInclusive,  
    has positiveValueConnotation,  
    has negativeValueConnotation,  
    has isDeprecated,   
    plays contains_valueDefinition,   
    plays contains_mappingToReferenceScale,   
    plays iscontained_scale,   
    plays refers_unit,   
    plays isrefered_scale,   
    plays isrefered_possibleScale,   
    plays isrefered_defaultScale,   
    plays isrefered_allPossibleScale  ; 

 MeasurementUnit  sub DefinedThing, abstract,
    has isDeprecated,   
    plays iscontained_unit,   
    plays isrefered_referenceUnit,   
    plays isrefered_unit,   
    plays isrefered_baseUnit  ; 

 ModelLogEntry  sub Thing, 
    has languageCode,  
    has content,  
    has createdOn,  
    has level,  
    has affectedItemIid,   
    plays iscontained_logEntry,   
    plays refers_category,   
    plays refers_author  ; 

 ModelReferenceDataLibrary  sub ReferenceDataLibrary,   
    plays iscontained_requiredRdl  ; 

 MultiRelationship  sub Relationship,
    plays refers_relatedThing  ; 

 MultiRelationshipRule  sub Rule,
    has minRelated,  
    has maxRelated,   
    plays refers_relationCategory,   
    plays refers_relatedCategory  ; 

 NaturalLanguage  sub Thing, 
    has languageCode,  
    has nativeName,  
    has name,   
    plays iscontained_naturalLanguage  ; 

 NestedElement  sub Thing, 
    has name,  
    has shortName,  
    has isVolatile,   
    plays contains_nestedParameter,   
    plays iscontained_nestedElement,   
    plays refers_rootElement,   
    plays refers_elementUsage,   
    plays refers_owner,   
    plays isrefered_referencedElement  ; 

 NestedParameter  sub Thing, 
    has path,  
    has formula,  
    has actualValue,  
    has isVolatile,   
    plays iscontained_nestedParameter,   
    plays refers_associatedParameter,   
    plays refers_actualState,   
    plays refers_owner  ; 

 NotExpression  sub BooleanExpression,   
    plays refers_term  ; 

 Option  sub DefinedThing,   
    plays contains_nestedElement,   
    plays iscontained_option,   
    plays refers_category,   
    plays isrefered_excludeOption,   
    plays isrefered_defaultOption,   
    plays isrefered_actualOption  ; 

 OrExpression  sub BooleanExpression,   
    plays refers_term  ; 

 OrdinalScale  sub MeasurementScale,  
    has useShortNameValues  ; 

 Organization  sub Thing,
    has name,  
    has shortName,  
    has isDeprecated,   
    plays iscontained_organization,   
    plays isrefered_organization,   
    plays isrefered_publisher  ; 

 Parameter  sub ParameterOrOverrideBase,  
    has allowDifferentOwnerOfOverride,  
    has expectsOverride,   
    plays contains_valueSet,   
    plays iscontained_parameter,   
    plays refers_requestedBy,   
    plays isrefered_parameter  ; 

 ParameterBase  sub Thing, abstract,
    has isOptionDependent,   
    plays refers_parameterType,   
    plays refers_scale,   
    plays refers_stateDependence,   
    plays refers_group,   
    plays refers_owner,   
    plays isrefered_associatedParameter  ; 

 ParameterGroup  sub Thing, 
    has name,   
    plays iscontained_parameterGroup,   
    plays refers_containingGroup,   
    plays isrefered_group,   
    plays isrefered_containingGroup  ; 

 ParameterOrOverrideBase  sub ParameterBase, abstract,
    plays contains_parameterSubscription,   
    plays isrefered_publishedParameter  ; 

 ParameterOverride  sub ParameterOrOverrideBase,  
    has isOptionDependent,   
    plays contains_valueSet,   
    plays iscontained_parameterOverride,   
    plays refers_parameter,   
    plays refers_parameterType,   
    plays refers_scale,   
    plays refers_stateDependence,   
    plays refers_group  ; 

 ParameterOverrideValueSet  sub ParameterValueSetBase,   
    plays iscontained_valueSet,   
    plays refers_actualState,   
    plays refers_actualOption,   
    plays refers_parameterValueSet  ; 

 ParameterSubscription  sub ParameterBase,  
    has isOptionDependent,   
    plays contains_valueSet,   
    plays iscontained_parameterSubscription,   
    plays refers_parameterType,   
    plays refers_scale,   
    plays refers_stateDependence,   
    plays refers_group  ; 

 ParameterSubscriptionValueSet  sub Thing, 
    has valueSwitch,  
    has computed,  
    has manual,  
    has reference,  
    has actualValue,   
    plays iscontained_valueSet,   
    plays refers_subscribedValueSet,   
    plays refers_actualState,   
    plays refers_actualOption,   
    plays refers_owner  ; 

 ParameterType  sub DefinedThing, abstract,
    has numberOfValues,  
    has symbol,  
    has isDeprecated,   
    plays iscontained_parameterType,   
    plays refers_category,   
    plays isrefered_parameterType  ; 

 ParameterTypeComponent  sub Thing, 
    has shortName,   
    plays iscontained_component,   
    plays refers_parameterType,   
    plays refers_scale  ; 

 ParameterValueSet  sub ParameterValueSetBase,   
    plays iscontained_valueSet,   
    plays isrefered_parameterValueSet  ; 

 ParameterValueSetBase  sub Thing, abstract,
    has valueSwitch,  
    has published,  
    has formula,  
    has computed,  
    has manual,  
    has reference,  
    has actualValue,   
    plays refers_actualState,   
    plays refers_actualOption,   
    plays refers_owner,   
    plays isrefered_subscribedValueSet  ; 

 ParameterizedCategoryRule  sub Rule,   
    plays refers_category,   
    plays refers_parameterType  ; 

 ParametricConstraint  sub Thing,  
    plays contains_expression,  
    plays iscontained_parametricConstraint,   
    plays refers_topExpression,   
    plays refers_owner  ; 

 Participant  sub Thing, 
    has isActive,   
    plays iscontained_participant,   
    plays refers_person,   
    plays refers_role,   
    plays refers_domain,   
    plays refers_selectedDomain,   
    plays isrefered_creator  ; 

 ParticipantPermission  sub Thing, 
    has accessRight,  
    has objectClass,  
    has isDeprecated,   
    plays iscontained_participantPermission  ; 

 ParticipantRole  sub DefinedThing,
    has isDeprecated,   
    plays contains_participantPermission,   
    plays iscontained_participantRole,   
    plays isrefered_role,   
    plays isrefered_defaultParticipantRole  ; 

 Person sub Thing,
    has givenName,  
    has surname,  
    has name,  
    has organizationalUnit,  
    has isActive,  
    has password,  
    has shortName,  
    has isDeprecated,   
    plays contains_emailAddress,   
    plays contains_telephoneNumber,   
    plays contains_userPreference,   
    plays iscontained_person,   
    plays refers_organization,   
    plays refers_defaultDomain,   
    plays refers_role,   
    plays refers_defaultEmailAddress,   
    plays refers_defaultTelephoneNumber,   
    plays isrefered_lockedBy,   
    plays isrefered_author,   
    plays isrefered_person  ; 

 PersonPermission  sub Thing, 
    has accessRight,  
    has objectClass,  
    has isDeprecated,   
    plays iscontained_personPermission  ; 

 PersonRole  sub DefinedThing,  
    has isDeprecated,   
    plays contains_personPermission,   
    plays iscontained_personRole,   
    plays isrefered_role,   
    plays isrefered_defaultPersonRole  ; 

 PossibleFiniteState  sub DefinedThing,   
    plays iscontained_possibleState,   
    plays refers_owner,   
    plays isrefered_possibleState,   
    plays isrefered_defaultState  ; 

 PossibleFiniteStateList  sub DefinedThing,   
    plays contains_possibleState,   
    plays iscontained_possibleFiniteStateList,   
    plays refers_defaultState,   
    plays refers_category,   
    plays refers_owner,   
    plays isrefered_possibleFiniteStateList  ; 

 PrefixedUnit  sub ConversionBasedUnit,  
    has conversionFactor,  
    has name,  
    has shortName,   
    plays refers_prefix  ; 

 Publication  sub Thing, 
    has createdOn,  
    plays iscontained_publication,   
    plays refers_domain,   
    plays refers_publishedParameter  ; 

 QuantityKind  sub ScalarParameterType, abstract,
    has quantityDimensionSymbol,  
    has quantityDimensionExpression,  
    has quantityDimensionExponent,   
    plays refers_possibleScale,   
    plays refers_defaultScale,   
    plays refers_allPossibleScale,   
    plays isrefered_referenceQuantityKind,   
    plays isrefered_quantityKind,   
    plays isrefered_baseQuantityKind,   
    plays isrefered_general  ; 

 QuantityKindFactor  sub Thing, 
    has exponent,   
    plays iscontained_quantityKindFactor,   
    plays refers_quantityKind  ; 

 RatioScale  sub MeasurementScale  ; 

 ReferenceDataLibrary  sub DefinedThing, abstract,
    plays contains_definedCategory,   
    plays contains_parameterType,   
    plays contains_scale,   
    plays contains_unitPrefix,   
    plays contains_unit,   
    plays contains_fileType,   
    plays contains_glossary,   
    plays contains_referenceSource,   
    plays contains_rule,   
    plays contains_constant,   
    plays refers_baseQuantityKind,   
    plays refers_baseUnit,   
    plays refers_requiredRdl  ; 

 ReferenceSource  sub DefinedThing,  
    has versionIdentifier,  
    has versionDate,  
    has author,  
    has publicationYear,  
    has language,  
    has isDeprecated,   
    plays iscontained_referenceSource,   
    plays refers_publisher,   
    plays refers_publishedIn,   
    plays refers_category,   
    plays isrefered_source,   
    plays isrefered_externalFormat,   
    plays isrefered_publishedIn  ; 

 ReferencerRule  sub Rule,  
    has minReferenced,  
    has maxReferenced,   
    plays refers_referencingCategory,   
    plays refers_referencedCategory  ; 

 RelationalExpression  sub BooleanExpression,  
    has relationalOperator,  
    has value,   
    plays refers_parameterType,   
    plays refers_scale  ; 

 Relationship  sub Thing, abstract,
    plays iscontained_relation,   
    plays refers_category,   
    plays refers_owner  ; 

 Requirement sub SimpleParameterizableThing,  
    has isDeprecated,   
    plays contains_parametricConstraint,   
    plays iscontained_requirement,   
    plays refers_group,   
    plays refers_category  ; 

 RequirementsContainer  sub DefinedThing, abstract,
    plays contains_group,   
    plays refers_owner  ; 

 RequirementsGroup  sub RequirementsContainer,   
    plays iscontained_group,   
    plays isrefered_group  ; 

 RequirementsSpecification  sub RequirementsContainer,  
    has isDeprecated,   
    plays contains_requirement,   
    plays iscontained_requirementsSpecification  ; 

 Rule  sub DefinedThing, abstract,
    has isDeprecated,   
    plays iscontained_rule,   
    plays isrefered_rule  ; 

 RuleVerification  sub Thing, abstract,
    has isActive,  
    has executedOn,  
    has status,  
    has name,   
    plays contains_violation,   
    plays iscontained_ruleVerification,   
    plays refers_owner  ; 

 RuleVerificationList  sub DefinedThing,   
    plays contains_ruleVerification,   
    plays iscontained_ruleVerificationList,   
    plays refers_owner  ; 

 RuleViolation  sub Thing, 
    has description,  
    has violatingThing,   
    plays iscontained_violation  ; 

 ScalarParameterType  sub ParameterType, abstract;

 ScaleReferenceQuantityValue  sub Thing, 
    has value,   
    plays iscontained_referenceQuantityValue,   
    plays refers_scale  ; 

 ScaleValueDefinition  sub DefinedThing,  
    has value,   
    plays iscontained_valueDefinition,   
    plays isrefered_referenceScaleValue,   
    plays isrefered_dependentScaleValue; 

 SimpleParameterValue  sub Thing, 
    has value,   
    plays iscontained_parameterValue,   
    plays refers_parameterType,   
    plays refers_scale,   
    plays refers_owner  ; 

 SimpleParameterizableThing  sub DefinedThing, abstract,
    plays contains_parameterValue,
    plays refers_owner  ; 

 SimpleQuantityKind  sub QuantityKind  ; 

 SimpleUnit  sub MeasurementUnit  ; 

 SiteDirectory  sub TopContainer,  
    has createdOn,  
    has name,  
    has shortName,   
    plays contains_organization,   
    plays contains_person,   
    plays contains_participantRole,   
    plays contains_siteReferenceDataLibrary,   
    plays contains_model,   
    plays contains_personRole,   
    plays contains_logEntry,   
    plays contains_domainGroup,   
    plays contains_domain,   
    plays contains_naturalLanguage,   
    plays refers_defaultParticipantRole,   
    plays refers_defaultPersonRole  ; 

 SiteLogEntry  sub Thing, 
    has createdOn,  
    has languageCode,  
    has content,  
    has level,  
    has affectedItemIid,   
    plays iscontained_logEntry,   
    plays refers_category,   
    plays refers_author  ; 

 SiteReferenceDataLibrary  sub ReferenceDataLibrary,  
    has isDeprecated,  
    plays iscontained_siteReferenceDataLibrary,   
    plays isrefered_requiredRdl  ; 

 SpecializedQuantityKind  sub QuantityKind,   
    plays refers_general  ; 

 TelephoneNumber  sub Thing, 
    has value,  
    has vcardType,   
    plays iscontained_telephoneNumber,   
    plays isrefered_defaultTelephoneNumber  ; 

 Term  sub DefinedThing,  
    has isDeprecated,   
    plays iscontained_term  ; 

 TextParameterType  sub ScalarParameterType  ; 

 Thing  sub entity, abstract,
    has iid,  
    has revisionNumber,  
    has classKind,
    has lastModifiedOn,
    plays isrefered_source,   
    plays isrefered_target,   
    plays isrefered_relatedThing  ; 

 TimeOfDayParameterType  sub ScalarParameterType  ; 

 TopContainer  sub Thing, abstract;

 UnitFactor  sub Thing, 
    has exponent,   
    plays iscontained_unitFactor,   
    plays refers_unit  ; 

 UnitPrefix  sub DefinedThing,  
    has conversionFactor,  
    has isDeprecated,   
    plays iscontained_unitPrefix,   
    plays isrefered_prefix  ; 

 UserPreference  sub Thing, 
    has value,  
    has shortName,   
    plays iscontained_userPreference  ; 
	
 UserRuleVerification  sub RuleVerification,
    has name,   
    plays refers_rule  ; 

#--------------------------------------------
# Relations Definition
#-------------------------------------------- 

 Containement_actualState  sub relation, 
    relates contains_actualState,
    relates iscontained_actualState ;

 Reference_possibleState  sub relation, 
    relates refers_possibleState,
    relates isrefered_possibleState ;

 Reference_owner  sub relation, 
    relates refers_owner,
    relates isrefered_owner ;

 Reference_actualState  sub relation ,
    relates refers_actualState,
    relates isrefered_actualState;

 Containement_actualFiniteStateList  sub relation ,
    relates contains_actualFiniteStateList,
    relates iscontained_actualFiniteStateList ;

 Reference_possibleFiniteStateList  sub relation ,
    relates refers_possibleFiniteStateList,
    relates isrefered_possibleFiniteStateList ;

 Reference_excludeOption  sub relation ,
    relates refers_excludeOption,
    relates isrefered_excludeOption ;

 Reference_stateDependence  sub relation ,
    relates refers_stateDependence,
    relates isrefered_stateDependence ;

 Containement_alias  sub relation ,
    relates contains_alias,
    relates iscontained_alias ;

 Reference_term  sub relation ,
    relates refers_term,
    relates isrefered_term ;

 Reference_source  sub relation ,
    relates refers_source,
    relates isrefered_source ;

 Reference_target  sub relation ,
    relates refers_target,
    relates isrefered_target ;

 Reference_relationCategory  sub relation ,
    relates refers_relationCategory,
    relates isrefered_relationCategory ;

 Reference_sourceCategory  sub relation ,
    relates refers_sourceCategory,
    relates isrefered_sourceCategory ;

 Reference_targetCategory  sub relation ,
    relates refers_targetCategory,
    relates isrefered_targetCategory ;

 Containement_expression  sub relation ,
    relates contains_expression,
    relates iscontained_expression ;

 Reference_topExpression  sub relation ,
    relates refers_topExpression,
    relates isrefered_topExpression ;

 Containement_definedCategory  sub relation ,
    relates contains_definedCategory,
    relates iscontained_definedCategory ;

 Reference_superCategory  sub relation ,
    relates refers_superCategory,
    relates isrefered_superCategory ;

 Reference_category  sub relation ,
    relates refers_category,
    relates isrefered_category ;

 Reference_containingCategory  sub relation ,
    relates refers_containingCategory,
    relates isrefered_containingCategory ;

 Reference_containedCategory  sub relation ,
    relates refers_containedCategory,
    relates isrefered_containedCategory ;

 Reference_relatedCategory  sub relation ,
    relates refers_relatedCategory,
    relates isrefered_relatedCategory ;

 Reference_referencingCategory  sub relation ,
    relates refers_referencingCategory,
    relates isrefered_referencingCategory;

 Reference_referencedCategory  sub relation ,
    relates refers_referencedCategory,
    relates isrefered_referencedCategory ;

 Containement_citation  sub relation ,
    relates contains_citation,
    relates iscontained_citation ;

 Containement_commonFileStore  sub relation ,
    relates contains_commonFileStore,
    relates iscontained_commonFileStore;

 Containement_component  sub relation ,
    relates contains_component,
    relates iscontained_component ;

 Containement_constant  sub relation ,
    relates contains_constant,
    relates iscontained_constant ;

 Reference_parameterType  sub relation ,
    relates refers_parameterType,
    relates isrefered_parameterType ;

 Reference_scale  sub relation ,
    relates refers_scale,
    relates isrefered_scale ;

 Reference_referenceUnit  sub relation ,
    relates refers_referenceUnit,
    relates isrefered_referenceUnit ;

 Containement_definition  sub relation ,
    relates contains_definition,
    relates iscontained_definition ;

 Containement_hyperLink  sub relation ,
    relates contains_hyperLink,
    relates iscontained_hyperLink ;

 Containement_quantityKindFactor  sub relation ,
    relates contains_quantityKindFactor,
    relates iscontained_quantityKindFactor ;

 Containement_unitFactor  sub relation ,
    relates contains_unitFactor,
    relates iscontained_unitFactor ;

 Containement_domainFileStore  sub relation ,
    relates contains_domainFileStore,
    relates iscontained_domainFileStore ;

 Containement_domain  sub relation ,
    relates contains_domain,
    relates iscontained_domain ;

 Reference_domain  sub relation ,
    relates refers_domain,
    relates isrefered_domain ;

 Reference_activeDomain  sub relation ,
    relates refers_activeDomain,
    relates isrefered_activeDomain ;

 Reference_requestedBy  sub relation ,
    relates refers_requestedBy,
    relates isrefered_requestedBy ;

 Reference_selectedDomain  sub relation ,
    relates refers_selectedDomain,
    relates isrefered_selectedDomain ;

 Reference_defaultDomain  sub relation ,
    relates refers_defaultDomain,
    relates isrefered_defaultDomain ;

 Containement_domainGroup  sub relation ,
    relates contains_domainGroup,
    relates iscontained_domainGroup ;

 Containement_containedElement  sub relation ,
    relates contains_containedElement,
    relates iscontained_containedElement ;

 Containement_parameter  sub relation ,
    relates contains_parameter,
    relates iscontained_parameter ;

 Containement_parameterGroup  sub relation ,
    relates contains_parameterGroup,
    relates iscontained_parameterGroup ;

 Containement_element  sub relation ,
    relates contains_element,
    relates iscontained_element ;

 Reference_referencedElement  sub relation ,
    relates refers_referencedElement,
    relates isrefered_referencedElement ;

 Reference_elementDefinition  sub relation ,
    relates refers_elementDefinition,
    relates isrefered_elementDefinition ;

 Reference_topElement  sub relation ,
    relates refers_topElement,
    relates isrefered_topElement ;

 Reference_rootElement  sub relation ,
    relates refers_rootElement,
    relates isrefered_rootElement ;

 Containement_parameterOverride  sub relation ,
    relates contains_parameterOverride,
    relates iscontained_parameterOverride ;

 Reference_elementUsage  sub relation ,
    relates refers_elementUsage,
    relates isrefered_elementUsage ;

 Containement_emailAddress  sub relation ,
    relates contains_emailAddress,
    relates iscontained_emailAddress ;

 Reference_defaultEmailAddress  sub relation ,
    relates refers_defaultEmailAddress,
    relates isrefered_defaultEmailAddress ;

 Containement_logEntry  sub relation ,
    relates contains_logEntry,
    relates iscontained_logEntry ;

 Containement_iteration  sub relation ,
    relates contains_iteration,
    relates iscontained_iteration ;

 Reference_engineeringModelSetup  sub relation ,
    relates refers_engineeringModelSetup,
    relates isrefered_engineeringModelSetup ;

 Containement_participant  sub relation ,
    relates contains_participant,
    relates iscontained_participant ;

 Containement_requiredRdl  sub relation ,
    relates contains_requiredRdl,
    relates iscontained_requiredRdl ;

 Containement_iterationSetup  sub relation ,
    relates contains_iterationSetup,
    relates iscontained_iterationSetup ;

 Containement_model  sub relation ,
    relates contains_model,
    relates iscontained_model ;

 Containement_valueDefinition  sub relation ,
    relates contains_valueDefinition,
    relates iscontained_valueDefinition;

 Containement_correspondence  sub relation ,
    relates contains_correspondence,
    relates iscontained_correspondence ;

 Containement_externalIdentifierMap  sub relation ,
    relates contains_externalIdentifierMap,
    relates iscontained_externalIdentifierMap ;

 Reference_externalFormat  sub relation ,
    relates refers_externalFormat,
    relates isrefered_externalFormat ;

 Containement_fileRevision  sub relation ,
    relates contains_fileRevision,
    relates iscontained_fileRevision ;

 Containement_file  sub relation ,
    relates contains_file,
    relates iscontained_file ;

 Reference_lockedBy  sub relation ,
    relates refers_lockedBy,
    relates isrefered_lockedBy ;

 Reference_creator  sub relation ,
    relates refers_creator,
    relates isrefered_creator ;

 Reference_containingFolder  sub relation ,
    relates refers_containingFolder,
    relates isrefered_containingFolder ;

 Reference_fileType  sub relation ,
    relates refers_fileType,
    relates isrefered_fileType ;

 Containement_folder  sub relation ,
    relates contains_folder,
    relates iscontained_folder ;

 Containement_fileType  sub relation ,
    relates contains_fileType,
    relates iscontained_fileType ;

 Containement_term  sub relation ,
    relates contains_term,
    relates iscontained_term ;

 Containement_glossary  sub relation ,
    relates contains_glossary,
    relates iscontained_glossary ;

 Containement_option  sub relation ,
    relates contains_option,
    relates iscontained_option;

 Containement_publication  sub relation ,
    relates contains_publication,
    relates iscontained_publication ;

 Containement_possibleFiniteStateList  sub relation ,
    relates contains_possibleFiniteStateList,
    relates iscontained_possibleFiniteStateList ;

 Containement_relation  sub relation ,
    relates contains_relation,
    relates iscontained_relation;
	
 Containement_requirementsSpecification  sub relation ,
    relates contains_requirementsSpecification,
    relates iscontained_requirementsSpecification ;

 Containement_ruleVerificationList  sub relation ,
    relates contains_ruleVerificationList,
    relates iscontained_ruleVerificationList ;

 Reference_iterationSetup  sub relation ,
    relates refers_iterationSetup,
    relates isrefered_iterationSetup ;

 Reference_defaultOption  sub relation ,
    relates refers_defaultOption,
    relates isrefered_defaultOption ;

 Reference_sourceIterationSetup  sub relation ,
    relates refers_sourceIterationSetup,
    relates isrefered_sourceIterationSetup ;

 Containement_referenceQuantityValue  sub relation ,
    relates contains_referenceQuantityValue,
    relates iscontained_referenceQuantityValue ;

 Reference_referenceQuantityKind  sub relation ,
    relates refers_referenceQuantityKind,
    relates isrefered_referenceQuantityKind ;

 Containement_mappingToReferenceScale  sub relation ,
    relates contains_mappingToReferenceScale,
    relates iscontained_mappingToReferenceScale ;

 Reference_referenceScaleValue  sub relation ,
    relates refers_referenceScaleValue,
    relates isrefered_referenceScaleValue ;

 Reference_dependentScaleValue  sub relation ,
    relates refers_dependentScaleValue,
    relates isrefered_dependentScaleValue ;

 Containement_scale  sub relation ,
    relates contains_scale,
    relates iscontained_scale ;

 Reference_unit  sub relation ,
    relates refers_unit,
    relates isrefered_unit ;

 Reference_possibleScale  sub relation ,
    relates refers_possibleScale,
    relates isrefered_possibleScale ;

 Reference_defaultScale  sub relation ,
    relates refers_defaultScale,
    relates isrefered_defaultScale ;

 Reference_allPossibleScale  sub relation ,
    relates refers_allPossibleScale,
    relates isrefered_allPossibleScale ;

 Containement_unit  sub relation ,
    relates contains_unit,
    relates iscontained_unit ;

 Reference_baseUnit  sub relation ,
    relates refers_baseUnit,
    relates isrefered_baseUnit ;

 Reference_author  sub relation ,
    relates refers_author,
    relates isrefered_author ;

 Reference_relatedThing  sub relation ,
    relates refers_relatedThing,
    relates isrefered_relatedThing ;

 Containement_naturalLanguage  sub relation ,
    relates contains_naturalLanguage,
    relates iscontained_naturalLanguage ;

 Containement_nestedParameter  sub relation ,
    relates contains_nestedParameter,
    relates iscontained_nestedParameter ;

 Containement_nestedElement  sub relation ,
    relates contains_nestedElement,
    relates iscontained_nestedElement ;

 Reference_associatedParameter  sub relation ,
    relates refers_associatedParameter,
    relates isrefered_associatedParameter ;

 Reference_actualOption  sub relation ,
    relates refers_actualOption,
    relates isrefered_actualOption ;

 Containement_organization  sub relation ,
    relates contains_organization,
    relates iscontained_organization ;

 Reference_organization  sub relation ,
    relates refers_organization,
    relates isrefered_organization ;

 Reference_publisher  sub relation ,
    relates refers_publisher,
    relates isrefered_publisher ;

 Containement_valueSet  sub relation ,
    relates contains_valueSet,
    relates iscontained_valueSet ;

 Reference_parameter  sub relation ,
    relates refers_parameter,
    relates isrefered_parameter ;

 Reference_group  sub relation ,
    relates refers_group,
    relates isrefered_group ;

 Reference_containingGroup  sub relation ,
    relates refers_containingGroup,
    relates isrefered_containingGroup ;

 Containement_parameterSubscription  sub relation ,
    relates contains_parameterSubscription,
    relates iscontained_parameterSubscription ;

 Reference_publishedParameter  sub relation ,
    relates refers_publishedParameter,
    relates isrefered_publishedParameter ;

 Reference_parameterValueSet  sub relation ,
    relates refers_parameterValueSet,
    relates isrefered_parameterValueSet ;

 Reference_subscribedValueSet  sub relation ,
    relates refers_subscribedValueSet,
    relates isrefered_subscribedValueSet ;

 Containement_parameterType  sub relation ,
    relates contains_parameterType,
    relates iscontained_parameterType ;

 Containement_parametricConstraint  sub relation ,
    relates contains_parametricConstraint,
    relates iscontained_parametricConstraint ;

 Reference_person  sub relation ,
    relates refers_person,
    relates isrefered_person ;

 Reference_role  sub relation ,
    relates refers_role,
    relates isrefered_role ;

 Containement_participantPermission  sub relation ,
    relates contains_participantPermission,
    relates iscontained_participantPermission ;

 Containement_participantRole  sub relation ,
    relates contains_participantRole,
    relates iscontained_participantRole ;

 Reference_defaultParticipantRole  sub relation ,
    relates refers_defaultParticipantRole,
    relates isrefered_defaultParticipantRole ;

 Containement_telephoneNumber  sub relation ,
    relates contains_telephoneNumber,
    relates iscontained_telephoneNumber ;

 Containement_userPreference  sub relation ,
    relates contains_userPreference,
    relates iscontained_userPreference ;

 Containement_person  sub relation ,
    relates contains_person,
    relates iscontained_person ;

 Reference_defaultTelephoneNumber  sub relation ,
    relates refers_defaultTelephoneNumber,
    relates isrefered_defaultTelephoneNumber ;

 Containement_personPermission  sub relation ,
    relates contains_personPermission,
    relates iscontained_personPermission ;

 Containement_personRole  sub relation ,
    relates contains_personRole,
    relates iscontained_personRole ;

 Reference_defaultPersonRole  sub relation ,
    relates refers_defaultPersonRole,
    relates isrefered_defaultPersonRole ;

 Containement_possibleState  sub relation ,
    relates contains_possibleState,
    relates iscontained_possibleState ;

 Reference_defaultState  sub relation ,
    relates refers_defaultState,
    relates isrefered_defaultState ;

 Reference_prefix  sub relation ,
    relates refers_prefix,
    relates isrefered_prefix ;

 Reference_quantityKind  sub relation ,
    relates refers_quantityKind,
    relates isrefered_quantityKind ;

 Reference_baseQuantityKind  sub relation ,
    relates refers_baseQuantityKind,
    relates isrefered_baseQuantityKind ;

 Reference_general  sub relation ,
    relates refers_general,
    relates isrefered_general ;

 Containement_unitPrefix  sub relation ,
    relates contains_unitPrefix,
    relates iscontained_unitPrefix ;

 Containement_referenceSource  sub relation ,
    relates contains_referenceSource,
    relates iscontained_referenceSource ;

 Containement_rule  sub relation ,
    relates contains_rule,
    relates iscontained_rule ;

 Reference_requiredRdl  sub relation ,
    relates refers_requiredRdl,
    relates isrefered_requiredRdl ;

 Reference_publishedIn  sub relation ,
    relates refers_publishedIn,
    relates isrefered_publishedIn ;

 Containement_requirement  sub relation ,
    relates contains_requirement,
    relates iscontained_requirement ;

 Containement_group  sub relation ,
    relates contains_group,
    relates iscontained_group ;

 Reference_rule  sub relation ,
    relates refers_rule,
    relates isrefered_rule ;

 Containement_violation  sub relation ,
    relates contains_violation,
    relates iscontained_violation ;

 Containement_ruleVerification  sub relation ,
    relates contains_ruleVerification,
    relates iscontained_ruleVerification ;

 Containement_parameterValue  sub relation ,
    relates contains_parameterValue,
    relates iscontained_parameterValue ;

 Containement_siteReferenceDataLibrary  sub relation ,
    relates contains_siteReferenceDataLibrary,
    relates iscontained_siteReferenceDataLibrary ;
